//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuSistem.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUNLER
    {
        public int Urunid { get; set; }
        public string Urunad { get; set; }
        public string UrunAd { get; internal set; }
        public string UrunDetay { get; set; }
        public Nullable<int> UrunKategori { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public string UrunGorsel { get; set; }
    
        public virtual TBLKATEGORİLER TBLKATEGORİLER { get; set; }
    }
}
